site_name: Intro to Data Engineering
site_author: 'Vinay Krishna'
site_url: 'https://vinkrish.github.io/DataEngineering/'
theme:
  name: 'material'
  
# Repository
repo_name: 'vinkrish/DataEngineering'
repo_url: 'https://github.com/vinkrish/DataEngineering'

extra_javascript:
  # Add MathJax support
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML'

markdown_extensions:
  - mdx_math

# Navigation
nav:
  - About: index.md
  - Info: info.md
  - Data Model: data_model.md
  - Data Science: data_science.md
  - Data Warehouse: data_warehouse.md
  - Data Lakes: data_lakes.md
  - Data Quality: data_quality.md
  - Data Analysis Process: dap.md
  - Big Data: big_data.md
  - Terminology: terminology.md